### ISSUE TITLE
HeapSnapshots

### ISSUE THREAD

**Issue by bmeck** [nearform/node-clinic-doctor#101]
Hiya!

I'm working on some heap snapshot stuff, and I am trying to integrate it with `clinic doctor`. However, since heap snapshots take a significant CPU and Memory spike when being generated I was seeking to find a way to mark the time which I am performing the snapshot as being done by instrumentation. Is there a clear way to do this currently / is there a recommendation on how I should approach this? It might be incompatible with the `doctor` workflow and need an entirely new command, but it seems like it would be nice to gather all the data from the same PID.

**Comment by AndreasMadsen** [comment]
HI @bmeck. James told me about this.

Can you tell me why this is specific to doctor "diagnosing the type of issue and providing a recommendation" and what problem it solves?

My immediate thought is that this doesn't belong in `clinic doctor` specifically but in another `clinic` tool, like we also have `clinic 0x`.

You are welcome to seal our injection setup in `index.js`, that will also make it very easy for you add another tool in `clinic`.

**Comment by mcollina** [comment]
I think it might be a separate tool. What problem would that tool solve?

---

There might be some parts of doctor that you might want to reuse. Let us know and we can easily extract them out.

Helping out in solving memory issues is something we were thinking on doing in the future. So we should definitely collaborate!

**Comment by bmeck** [comment]
@AndreasMadsen essentially I am gathering heap snapshots over the life of a process to give a proper recommendation on heap growth. Right now you can get the output of how much the heap grew in size, but not how it grew and it can even be very misleading for some kinds of use cases:

```mjs
global.foo = [];
setInterval(
  () => {
    global.foo = [
      global.foo,
      new Uint8Array(1024 * 1024).fill(Date.now())
    ];
  },
  1 * 100
);
```

Which shows as very low heap usage but very high RSS usage.

I could make a new command but then it would be separated from other trace data which would be nice to cross reference against. I would probably have my tool gather all of the statistics that `doctor` does so moving it out would be a little odd.

**Comment by mcollina** [comment]
@bmeck doctor retrieves all the data and then it applies some analysis and categorization on top. The categorization (and recommendation )would not make sense with such a disruptive action which is taking a heap snapshot. 

What would be the expected output of that heap diffing?
I think you want to create a different analysis and visualization if I understand it correctly.

**Comment by bmeck** [comment]
@mcollina you can create a well formed idea of exactly the [variables that grew](https://github.com/bmeck/snapshot-utils/blob/master/bin/what-variables-hold-new-objects.sh) / when with heap snapshots. Heap snapshots do a full GC prior to the dump which means we lose any scavenge data, but Heap Statistics show the scavenge data so we can correlate when new generations are being used heavily but not making it to the old generation and the opposite. 

The basic output would probably be something like:

![untitled drawing](https://user-images.githubusercontent.com/234659/35869489-c486b784-0b24-11e8-9d24-90c71ffcab82.png)

The size of growth can get a little [complicated though](http://bmeck.github.io/snapshot-utils/doc/manual/terms.html#closed-size) since there are multiple kinds of growth.

**Comment by AndreasMadsen** [comment]
@bmeck Please get back to us if you are still interested in this. But as this is not directly related to `clinic-doctor` I will close this issue.
