### ISSUE TITLE
Support clusters and multiprocess setups

### ISSUE THREAD

**Issue by AndreasMadsen** [nearform/node-clinic-doctor#102]
Currently, our injection works via `NODE_OPTIONS` and is thus propagated to all sub-processes. This causes some issues as each process will write to `node_trace.1.log`. https://github.com/nodejs/node/pull/18480 will eventually fix that.

However, it still won't be obvious what process the user wants to be analyzed with https://github.com/nodejs/node/pull/18480 in place it will be the master process. However, that is properly not what the user wants by default.

With https://github.com/nodejs/node/pull/18480 in place, it will also be possible to inspect each process with `clinic doctor --visualize-only`. However, that is not very obvious for a first-time user.

**Comment by mcollina** [comment]
I think we need a guide and some docs to get this done.
Il giorno ven 10 ago 2018 alle 14:03 Ruben Bridgewater <
notifications@github.com> ha scritto:

**Comment by BridgeAR** [comment]
Closing as resolved for now: we do not support cluster.
