### ISSUE TITLE
Explain why the CPU can go to 200%

### ISSUE THREAD

**Issue by mcollina** [nearform/node-clinic-doctor#109]
See https://github.com/nearform/node-clinic/issues/13#issuecomment-372228263.

**Comment by DylanC** [comment]
@mcollina - This seems to have been resolved here:
https://github.com/nearform/node-clinic/pull/46/commits/7aa91977bf77d9d5c5230ab8f8c2acdda74b1533

Do you just want a similar description on the Doctor readme?

**Comment by mcollina** [comment]
It's ok
