### ISSUE TITLE
visualize method not looking for correct file - ENOENT error

### ISSUE THREAD

**Issue by HowWeRollingham** [nearform/node-clinic-doctor#113]
The following code:
```
const ClinicDoctor = require('@nearform/clinic-doctor');
const doctor = new ClinicDoctor();

// this is so nodemon can signal doctor to finish collection and proceed to visualize
process.once('SIGUSR2', function () {
    process.kill(process.pid, 'SIGINT');
});

doctor.collect(['node', './index.js'], function (err, filepath) {
    doctor.visualize(filepath, filepath + '.html', function (err) {
        if (err) throw err;
    });
});
```

Results in the following error:
`Error: ENOENT: no such file or directory, open '220.clinic-doctor/220.clinic-doctor-traceevent'`
when the process is restarted.

I have run this without `nodemon` and the signal code above and it generates the report OK.  But I would really prefer the process to restart automatically.

I would guess that the trace file actually being created is the file `./node_trace.N.log` which *is* present.

What's going on here - is this a bug?

**Comment by mafintosh** [comment]
Should be fixed in latest. Mind trying again? :)
