### ISSUE TITLE
Generate report on Windows after proc.kill('SIGINT')`

### ISSUE THREAD

**Issue by lukaszewczak** [nearform/node-clinic-doctor#145]
Hi,

Thank you for a great tool. I try to use `node-clinic`  on my Windows 10 machine, but after I try to end my process using CTRL+C, nothing happens, the only process ends, without a report. 

I clone `node-clinic` repo and make `npm link` to it, and change this line https://github.com/nearform/node-clinic-doctor/blob/master/index.js#L75 into  
`/*if (os.platform() !== 'win32') */ proc.kill('SIGINT')`, to kill process on windows platform using `SIGINT` signal, and after i press CTRL+C in my command line, process end and report was analyzed.

I saw the comment in the code, but I don't know why, but at the moment it works for me when I use this 

```javascript
 process.once('SIGINT', function () {  proc.kill('SIGINT') })
```

```
C:\Projekty\Learn\node-clinic>npm version
{ clinic: '1.0.3',
  npm: '6.1.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.11.3',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.54',
  zlib: '1.2.11' }
```

**Comment by BridgeAR** [comment]
Thanks a lot for the report. @mafintosh you added this in a PR without further description. Can you outline the issue and do you think we can fix this one way or the other?

**Comment by mafintosh** [comment]
@BridgeAR See the comment in the code. We had a lot of issues with the sigint not being propagated on on Windows (the ctrl-c seems to be a special thing). If it works somehow now, I'm fine changing it obvs, but haven't seen this issue personally on windows still.

@lukaszewczak Do you have simple test case we can run to test it ourself?

**Comment by lukaszewczak** [comment]
Hi @mafintosh ,

So I  try to made a fork https://github.com/lukaszewczak/node-clinic-doctor, and put this change in the code (https://github.com/lukaszewczak/node-clinic-doctor/blob/master/index.js#L70)

```javascript
process.once('SIGINT', function () {
    proc.kill('SIGINT')
 })
```

And to test it I change two scripts:
1.  [cmd-collect-exit.test.js](https://github.com/lukaszewczak/node-clinic-doctor/blob/master/test/cmd-collect-exit.test.js) - I removed the code to skip test on Windows and I listen for child process `exit` event to test if it was killed by `SIGINT` signal
2. [cmd-collect-exit-sigint.script.js](https://github.com/lukaszewczak/node-clinic-doctor/blob/master/test/cmd-collect-exit-sigint.script.js) - I removed code `process.once('SIGINT')), because child process cant' capture this signal.

In general child process can't capture the signal on Windows, it is just killed immediately by it, just like in the [docs](https://nodejs.org/api/process.html#process_signal_events) , this is why the previous writen test can not pass.

```
Windows does not support sending signals, but Node.js offers some emulation with process.kill(), 
and subprocess.kill(). Sending signal 0 can be used to test for the existence of a process. 
Sending SIGINT, SIGTERM, and SIGKILL cause the unconditional termination of the target process.
```

But` 'SIGINT' from the terminal is supported on all platforms`, which is the case in [node-clinic-doctor] (https://github.com/lukaszewczak/node-clinic-doctor/blob/master/index.js#L70) where the code is listening for `SIGINT` signal on the main process, not a child process.


I hope that my attempt to explain this behavior is quite understandable.

**Comment by DylanC** [comment]
@lukaszewczak - Can you try this again with the latest versions of node clinic and doctor?

**Comment by lukaszewczak** [comment]
Hi @DylanC , I tested with `clinic doctor` version v5.0.0, and it works! :-). Thank you :-)
