### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by lukaszewczak** [nearform/node-clinic-doctor#147]
Hi,

I try to analyze my app, but unfortunately I still receive `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` after long time waiting for analising data. Traceevent file is 1,87 GB.

I generally run my application and run for about 4/5 minutes e2e tests.

```
Analysing data

<--- Last few GCs --->
 
[24700:00000212E1D051E0]  7831109 ms: Mark-sweep 1802.1 (1852.7) -> 1802.1 (1838.7) MB, 2021.3 / 0.0 ms  last resort GC in old space requested
[24700:00000212E1D051E0]  7832953 ms: Mark-sweep 1802.1 (1838.7) -> 1802.1 (1838.2) MB, 1843.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001DED02A5879 <JSObject>
    1: _onToken [C:\Projekty\Learn\node-clinic\node_modules\jsonparse\jsonparse.js:~342] [pc=0000032ABCACE55F](this=00000067E07A0029 <Parser map = 00000185D9FA8E21>,token=1,value=000002E504BEDBD9 <String[1]: {>)
    2: onToken [C:\Projekty\Learn\node-clinic\node_modules\JSONStream\index.js:~124] [pc=0000032ABCAD0AE0](this=00000067E07A0029 <Parser map = 00000185D9FA8E21>,token=1,value=000002E50...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::WasmDebugInfo::SetupForTesting
 6: v8::internal::WasmDebugInfo::SetupForTesting
 7: v8::internal::WasmDebugInfo::SetupForTesting
 8: v8::internal::WasmDebugInfo::SetupForTesting
 9: v8::internal::SharedFunctionInfo::SetScript
10: v8::internal::JSReceiver::class_name
11: v8::internal::SourcePositionTableIterator::Advance
12: v8::internal::SourcePositionTableIterator::Advance
13: 0000032ABC8043C1
```

Could you please guide me how I can make this analyze to work.

**Comment by AlanSl** [comment]
Hi Lukas, in the short term, I'd suggest trying a shorter benchmark - maybe 30 seconds initially, then try a minute, if that works try 1 minute 30, etc. If you can report back with the longest and largest (duration and mb of trace event file) profile you're able to successfully generate, that'd be really helpful. 

Usually with clinic, it's possible to get useful and meaningful information from profiles shorter than a minute. The intention is that for most cases, a user should be able to get usable clues on where to next focus their optimisation efforts from profiles as short as 10 seconds (though obviously there will be cases where this isn't appropriate).

More long term, supporting larger profiles is a current priority. 

@mafintosh do you think porting an equivalent of https://github.com/nearform/node-clinic-bubbleprof/pull/241 to Doctor would be a quick way to give something more useful in such cases?

**Comment by BridgeAR** [comment]
@mcollina @mafintosh instead of stop inspecting the trace events file, we could also go ahead and just stop collecting any further trace events after reaching a specific number of events. That way the actual inspected events would likely be higher than just stop visualizing them when the heap reaches a specific heights. I would go so far and let doctor close the running application on it's own and to print a warning why that has happened. What do you think?
