### ISSUE TITLE
CI failing on Windows, can't distinguish SIGKILL

### ISSUE THREAD

**Issue by AlanSl** [nearform/node-clinic-doctor#194]
We've been getting errors on Appveyor for a couple of releases now, since https://github.com/nearform/node-clinic-doctor/commit/c424544a3bf4ff16ea290d644f063311baaf0fcf - maybe we didn't notice because AppVeyor so often gives spurious errors... but this one isn't spurious, it seems to be because `process.exit(1)` and `process.kill(pid, 'SIGKILL')` aren't easily distinguished on Windows, but we have different behaviours for both and tests checking that both are handled differently.

Our Appveyor logs show that both `'--expose-gc', '-e', 'process.exit(1)'` and `'--expose-gc', '-e', 'process.kill(process.pid, "SIGKILL")'` give an exit code of `1` on Windows. 

So: 

- [x] Disable the failing SIGKILL test on Windows only - PR https://github.com/nearform/node-clinic-doctor/pull/195
- [ ] Check if we need different behaviour on Windows - see also somewhat related issue https://github.com/nearform/node-clinic-doctor/issues/145
- [ ] If we do, find some workaround to reliably distinguish the SIGKILL condition

**Comment by AndreasMadsen** [comment]
We don't use AppVeyor anymore and I don't see this issue.
