### ISSUE TITLE
Decouple format encoder and decoder

### ISSUE THREAD

**Issue by AndreasMadsen** [nearform/node-clinic-doctor#2]
Apparently, there is no half decent frame encoder and decoder in `npm`. At least, I can't find one. The format encoder and decoder should be decoupled from the code base and be generalized into variable sized messages.

file format:

```
| message-length 32bit | message | message-length 32bit | message | ...
```

**Comment by BridgeAR** [comment]
Is this still up to date? @kamil-mech @AlanSl @mafintosh?

**Comment by kamil-mech** [comment]
It's pretty much independent from the evolution of this repo - so to answer your question we need to ask someone who has orientation in the decoder/encoder ecosystem on npm - I imagine @mcollina or @AndreasMadsen  or @mafintosh  ?

**Comment by mcollina** [comment]
I think we can close this for now.
