### ISSUE TITLE
Tests broken if dependencies use mathfn v1.1.0

### ISSUE THREAD

**Issue by AlanSl** [nearform/node-clinic-doctor#200]
We have a few tests which check expected values against numbers calculated from a stack that includes `incBeta` from Andreas Madsen's [`mathfn`](https://github.com/AndreasMadsen/mathfn) (via `ttest` and `distributions`). [Latest release 1.1.0 to mathfn](https://github.com/AndreasMadsen/mathfn/commit/219a7a346bbbef2475f901ca93bfc7e90d0cc86c) changes the result of incBeta, dividing it by beta, and renames the old function `regualizedBeta`, which isn't exported.

So this is mostly a question for @AndreasMadsen if you can look at this:

 1. Should we treat the results based on the new incBeta as correct and update the expected values?
 2. Or should Doctor still be basing its calculations on the old incBeta logic, and the old expected results are correct for what Doctor is doing?

Also, longer term, given the [deprecation warning on mathfn](https://www.npmjs.com/package/mathfn), should we be swapping out that whole stack for something based on https://github.com/nearform/node-cephes ?

**Comment by AndreasMadsen** [comment]
> Or should Doctor still be basing its calculations on the old incBeta logic, and the old expected results are correct?

Is the correct answer. Properly the `ttest` module is wrong now.

> Also, longer term, given the deprecation warning on mathfn, should we be swapping out that whole stack for something based on https://github.com/nearform/node-cephes ?

yes. `mathfn` is very difficult to implement and maintain. That is why cephes now exists.

---

I will look into fixing ttest.

**Comment by AndreasMadsen** [comment]
I just published `ttest` version `2.0.0` which will fix it all.

**Comment by AndreasMadsen** [comment]
You might not get exactly the same values, as the new `ttest` should be more accurate.
