### ISSUE TITLE
Hapi load shedding recommend links are out of date

### ISSUE THREAD

**Issue by robmcguinness** [nearform/node-clinic-doctor#294]
Hapi docs urls changed recently which broke the previous links:

- `https://hapijs.com/api#new-serveroptions` **=>** `https://hapi.dev/api/#-serveroptionsload`

**Comment by DylanC** [comment]
@robmcguinness - Updated in this commit( f74b1dae6baf08279dbf040f6f9a4c1913533c09 ). Thanks.
