### ISSUE TITLE
⚠️ Detected data analysis issue

### ISSUE THREAD

**Issue by sam-w** [nearform/node-clinic-doctor#329]
I'm trying to profile a very CPU-heavy script. 
`clinic doctor -- node <script>` completes with what seems like a success, but I'm then shown an empty page with `⚠️ Detected data analysis issue`. Any ideas what's going on?

<img width="1607" alt="Screen Shot 2020-05-21 at 11 38 33 pm" src="https://user-images.githubusercontent.com/8063477/82564572-51fe5200-9bbc-11ea-8a0b-dc052bb59a4f.png">

**Comment by DylanC** [comment]
@sam-w - Is it possible you could send us the project to reproduce or a simple example to test?

**Comment by sam-w** [comment]
I'm not able to send the project I'm afraid, but I can definitely try to
take the open source dependencies and make a project that can reproduce the
issue. Before I do that, is there anything you can glean from my logs or
clinic data files?

**Comment by DylanC** [comment]
@sam-w - Can you attach the log please? We can look for any obvious error. Also if you can send a project to reproduce that would be fantastic!

**Comment by jasnell** [comment]
If you look in the `.clinic` directory there are profile files collected. Specifically, there is the processstat file that contains the data from the cpu profiler. Those files would be helpful in helping to identify what could be going on here.

**Comment by sam-w** [comment]
[Archive.zip](https://github.com/nearform/node-clinic-doctor/files/4666347/Archive.zip)
☝️ here you go! :)

**Comment by sam-w** [comment]
FWIWBTW `clinic flame` works just fine and is streets ahead of any other profiling I've done on Node. Amazing work peeps 🙏

**Comment by goto-bus-stop** [comment]
Doctor basically needs a bunch of async activity to happen before any of the measurements make sense. Fully synchronous scripts are better served by Flame.

**Comment by jasnell** [comment]
To explain that a bit more... A key part of doctor's analysis is that we compare multiple dimensions (CPU, event loop delay, memory usage, async activity, etc) to determine the classification of problem that may be experienced. Without those multiple dimensions the analysis is either incomplete or in some cases not possible. So when the application generates way too much of one kind of activity without any of the other there's no reasonable analysis that we can perform although we certainly can do a better job at failing more gracefully.

**Comment by sam-w** [comment]
Ah right, that makes sense :+1: If you want a test project, I got around to repackaging mine and removing the IP I'm not allowed to share:

[RulesEngine.zip](https://github.com/nearform/node-clinic-doctor/files/4668182/RulesEngine.zip)

- `nvm use`

**Comment by sam-w** [comment]
For now I'll close this and leave the graceful failing as a request for the next version. Keep up the good work!

**Comment by jasnell** [comment]
Awesome! Thank you @sam-w, that is definitely helpful
