### ISSUE TITLE
Error: process exited with exit code 3221225786 on Windows if child process doesn't catch SIGINT

### ISSUE THREAD

**Issue by AlanSl** [nearform/node-clinic-doctor#97]
Tested with node -v v9.4.0, clinic -v v0.5.1 and clinic doctor -v v1.0.1. To replicate:

- Run Doctor on any application that doesn't catch SIGINT. Easy example: just comment out `process.on('SIGINT'...` from node-clinic-examples slow-io. Real world example: a dev ApostropheCMS install.
- Ctrl-C to exit the process. Behaviour of index.js error detecting on line 62 `if (code !== 0 && signal !== 'SIGINT') {` varies:
  - On Linux, it sees signal === SIGINT and continues
  - On Windows, signal is `null` and code is `3221225786` (Windows' STATUS_CONTROL_C_EXIT exit code), which is treated as an error, so Doctor aborts profiling
  - Allow exit code 3221225786 on Windows, and the behaviour matches Linux: profile generates successfully

**Comment by mcollina** [comment]
Which version of Windows are you on? Which shell are you using (cmd, powershell, gitbash, ...)?

**Comment by AlanSl** [comment]
Windows 10, cmd

**Comment by AlanSl** [comment]
Same behaviour on PowerShell: error in master, works in #98. Testing gitbash now.
